<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <IsPackable>true</IsPackable>
	  <PackAsTool>true</PackAsTool>
	  <ToolCommandName>sqlcomp</ToolCommandName>
	  <Title>SQLComp</Title>
	  <Authors>Kristian Skov Johansen</Authors>
	  <Description>Compare tables between two SQL databases.</Description>
	  <RepositoryUrl>https://github.com/kris701/SQLComp</RepositoryUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SQLComp\SQLComp.csproj" />
  </ItemGroup>

	<PropertyGroup>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Version>1.0.5</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="logo.png" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
