<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>SQLComp</Title>
	  <Authors>Kristian Skov Johansen</Authors>
	  <Description>Compare tables between two SQL databases</Description>
	  <RepositoryUrl>https://github.com/kris701/SQLComp</RepositoryUrl>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

	<PropertyGroup>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Version>1.1.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<PropertyGroup>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="logo.png" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>
